import type { Metadata } from "next";
import localFonts from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import type { Viewport } from "next";

export const viewport: Viewport = {
  themeColor: "black",
};

const clashDisplay = localFonts({
  src: "../public/ClashDisplay-Variable.ttf",
});

export const metadata: Metadata = {
  title: "Ragas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={clashDisplay.className}>
        <ThemeProvider attribute="class">{children} </ThemeProvider>
      </body>
    </html>
  );
}
